# Generated by Django 3.2.13 on 2022-06-20 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='userComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userComment', to=settings.AUTH_USER_MODEL),
        ),
    ]
