# Generated by Django 3.2.13 on 2022-06-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_comments_usercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, choices=[('Toys', 'Toys'), ('Fashion', 'Fashion'), ('Home', 'Home'), ('Electronics', 'Electronics'), ('Other', 'Other')], max_length=11),
        ),
    ]
